[terminal]
[terminal.shell]
args = ["--login"]
program = "/usr/bin/zsh"


# Kanagawa Wave Alacritty Config
[env]
TERM = "xterm-256color"

[window]
opacity = 0.92
decorations = "full"
dynamic_title = true
startup_mode = "Windowed"
title = "Alacritty"
padding = { x = 8, y = 6 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 11.5

[colors.primary]
background = "#1F1F28"
foreground = "#DCD7BA"

[colors.normal]
black   = "#090618"
red     = "#C34043"
green   = "#76946A"
yellow  = "#C0A36E"
blue    = "#7E9CD8"
magenta = "#957FB8"
cyan    = "#6A9589"
white   = "#C8C093"

[colors.bright]
black   = "#727169"
red     = "#E82424"
green   = "#98BB6C"
yellow  = "#E6C384"
blue    = "#7FB4CA"
magenta = "#938AA9"
cyan    = "#7AA89F"
white   = "#DCD7BA"

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = true

[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

